name: jump_worlds
description: "A jumping game with generated worlds, enemies, and AI voices."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.8.0-278.2.beta

dependencies:
  flutter:
    sdk: flutter
  # UI
  cupertino_icons: ^1.0.8
  flutter_physics: ^0.1.0
  smooth_sheets: ^0.11.0
  flutter_animate: ^4.1.1+1
  auto_size_text: ^3.0.0
  shimmer: ^3.0.0
  octo_image: ^2.0.0
  flutter_tilt: ^3.2.0

  # UI Utils
  provider: ^6.1.5
  auto_route: ^9.2.2
  mesh_gradient: ^1.3.7
  share_plus: ^10.1.1
  url_launcher: ^6.1.10
  gaimon: ^1.4.0
  cached_network_image: ^3.3.0
  palette_generator: ^0.3.3+3
  lottie: ^3.1.3
  sliver_tools: ^0.2.12
  confetti: ^0.8.0
  jovial_svg: ^1.1.21

  # Platform Utils
  path_provider: ^2.1.2
  flutter_sound: ^9.25.5

  # Utils
  dart_mappable: ^4.4.0
  async: ^2.11.0
  fast_immutable_collections: ^11.0.3
  http: ^1.0.0
  rxdart: ^0.28.0
  universal_io: ^2.2.2
  characters: ^1.3.0
  hive: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_mappable_builder: ^4.4.0
  analyzer: ^7.1.0
  flutter_lints: ^5.0.0
  build_runner: ^2.4.14
  flutter_launcher_icons: ^0.14.0
  flutter_native_splash: ^2.3.9
  auto_route_generator: ^9.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/
    - assets/images/

  fonts:
    - family: HgiStrokeRounded
      fonts:
        - asset: assets/fonts/hgi-stroke-rounded.ttf
    - family: GeistMono
      fonts:
        - asset: assets/fonts/GeistMono-VariableFont_wght.ttf
    - family: RubikMonoOne
      fonts:
        - asset: assets/fonts/RubikMonoOne-Regular.ttf
          weight: 400

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/icon.png"
  image_path_android: "assets/images/icon.png"
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: true
  macos:
    generate: true
  windows:
    generate: false
  linux:
    generate: false
